### ISSUE TITLE
Upgrade the lib to the latest version 

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/uploader-ui#11]
- [x] Upgrade the demo ui to use the latest version of the lib
- [x] Make sure the wallet connection works
- [x] Test and validate that everything works as expected

**Comment by EnzoVezzaro** [comment]
This might not be as easy as we though as the team developed their own custom web3 connection component instead of connecting to the Uploader component's wallet. We need to redo what the other guys did and connect all using https://github.com/magiclabs/wagmi-magic-connector

**Comment by AnaLoznianu** [comment]
@EnzoVezzaro has this the potential of becoming a blocker? Everything is set for the Thursday release

**Comment by EnzoVezzaro** [comment]
this can become a blocked if I can't manage to pull it off. As the last resort, we can switch wallet's connection to what we have, while we work on a solution for MagicLink. Some like this:

<img width="567" alt="Screenshot 2023-10-18 at 12 13 09 PM" src="https://github.com/oceanprotocol/uploader-ui/assets/13741335/ad57db41-c82d-435a-bda8-a829601602a5">
<img width="567" alt="Screenshot 2023-10-18 at 12 15 39 PM" src="https://github.com/oceanprotocol/uploader-ui/assets/13741335/b707a4a3-3caa-4ed7-9503-2baf8d69fcba">

**Comment by EnzoVezzaro** [comment]
@AnaLoznianu can we close this issue or should we wait to do the latest fixes? and find more bugs potentialy 🐛😅

**Comment by AnaLoznianu** [comment]
Sure thing
